# Header
menu:
  Home: /
  Archives: /archives
  代理: /agent-agency
  关于: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
# - tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-109221704-1
google_ad_client: ca-pub-6193182060758164
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
